-- Quick migration to add enhanced perplexity fields
-- Copy and paste this directly into your Supabase SQL editor

BEGIN;

-- Add enhanced structured content fields to perplexity_news table
ALTER TABLE perplexity_news ADD COLUMN IF NOT EXISTS enhanced_title TEXT;
ALTER TABLE perplexity_news ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE perplexity_news ADD COLUMN IF NOT EXISTS key_points TEXT[];
ALTER TABLE perplexity_news ADD COLUMN IF NOT EXISTS why_it_matters TEXT;
ALTER TABLE perplexity_news ADD COLUMN IF NOT EXISTS structured_sources JSONB;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_perplexity_enhanced_title ON perplexity_news(enhanced_title);
CREATE INDEX IF NOT EXISTS idx_perplexity_summary ON perplexity_news(summary);
CREATE INDEX IF NOT EXISTS idx_perplexity_structured_sources ON perplexity_news USING GIN(structured_sources);

-- Add comments to document the enhancement
COMMENT ON COLUMN perplexity_news.enhanced_title IS 'Improved, engaging headline generated by AI';
COMMENT ON COLUMN perplexity_news.summary IS 'Executive summary of the article (2-3 sentences)';
COMMENT ON COLUMN perplexity_news.key_points IS 'Array of key points from the article';
COMMENT ON COLUMN perplexity_news.why_it_matters IS 'Analysis of broader significance and impact';
COMMENT ON COLUMN perplexity_news.structured_sources IS 'Source citations in structured JSON format';

COMMIT;

-- Verify the changes
SELECT 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'perplexity_news' 
AND column_name IN ('enhanced_title', 'summary', 'key_points', 'why_it_matters', 'structured_sources')
ORDER BY column_name;