import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseServiceRoleKey) {
  throw new Error('Missing Supabase environment variables')
}

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey)

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { searchParams } = new URL(request.url)
    const format = searchParams.get('format') || 'txt'

    // Fetch the news brief with article details
    const { data: brief, error } = await supabase
      .from('news_briefs')
      .select(`
        *,
        news_brief_articles(
          article_id,
          inclusion_reason,
          article_weight,
          articles(
            id,
            title,
            category,
            source,
            url
          )
        )
      `)
      .eq('id', params.id)
      .single()

    if (error || !brief) {
      return NextResponse.json(
        { error: 'News brief not found' },
        { status: 404 }
      )
    }

    // Format the content based on requested format
    let content: string
    let contentType: string
    let filename: string

    const formatDuration = (seconds: number) => {
      const mins = Math.floor(seconds / 60)
      const secs = seconds % 60
      return `${mins}:${secs.toString().padStart(2, '0')}`
    }

    switch (format) {
      case 'json':
        content = JSON.stringify(brief, null, 2)
        contentType = 'application/json'
        filename = `news-brief-${brief.id}.json`
        break
        
      case 'markdown':
        content = `# ${brief.title}

**Language:** ${brief.language}  
**Category:** ${brief.category}  
**Duration:** ${formatDuration(brief.estimated_duration_seconds)}  
**Word Count:** ${brief.actual_word_count}  
**Generated:** ${new Date(brief.created_at).toLocaleString()}  
**Model:** ${brief.openai_model_used}  
**Cost:** $${brief.generation_cost_usd.toFixed(6)}  

## TTS Script

${brief.content}

## Source Articles

${brief.news_brief_articles?.map((articleRef, index) => 
  `${index + 1}. **${articleRef.articles?.title}**  
   Source: ${articleRef.articles?.source}  
   Category: ${articleRef.articles?.category}  
   Reason: ${articleRef.inclusion_reason}  
   Weight: ${(articleRef.article_weight * 100).toFixed(1)}%  
   ${articleRef.articles?.url ? `URL: ${articleRef.articles.url}` : ''}
`).join('\n') || 'No source articles found'}

---
*Generated by TTS News Brief System*`
        contentType = 'text/markdown'
        filename = `news-brief-${brief.id}.md`
        break
        
      case 'txt':
      default:
        content = `${brief.title}
${'='.repeat(brief.title.length)}

Language: ${brief.language}
Category: ${brief.category}
Duration: ${formatDuration(brief.estimated_duration_seconds)}
Word Count: ${brief.actual_word_count}
Generated: ${new Date(brief.created_at).toLocaleString()}
Model: ${brief.openai_model_used}
Cost: $${brief.generation_cost_usd.toFixed(6)}

TTS SCRIPT
----------

${brief.content}

SOURCE ARTICLES
---------------

${brief.news_brief_articles?.map((articleRef, index) => 
  `${index + 1}. ${articleRef.articles?.title}
   Source: ${articleRef.articles?.source}
   Category: ${articleRef.articles?.category}
   Reason: ${articleRef.inclusion_reason}
   Weight: ${(articleRef.article_weight * 100).toFixed(1)}%
   ${articleRef.articles?.url ? `URL: ${articleRef.articles.url}` : ''}
`).join('\n') || 'No source articles found'}

Generated by TTS News Brief System`
        contentType = 'text/plain'
        filename = `news-brief-${brief.id}.txt`
        break
    }

    // Return the file as a download
    return new NextResponse(content, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': Buffer.byteLength(content, 'utf8').toString()
      }
    })

  } catch (error) {
    console.error('Error exporting news brief:', error)
    return NextResponse.json({
      error: 'Failed to export news brief',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 })
  }
}