import { createSlice, PayloadAction } from '@reduxjs/toolkit'

export type Language = 'en' | 'zh-CN' | 'zh-TW'

interface LanguageState {
  language: Language
  isHydrated: boolean
}

// Translation dictionaries (copied from language-provider.tsx)
const translations = {
  en: {
    // Header
    "app.title": "Panora",
    "nav.search": "Search",

    // Navigation
    "nav.home": "Home",
    "nav.topics": "Topics",
    "nav.bookmarks": "Bookmarks",
    "nav.profile": "Profile",

    // Topics
    "topics.all": "All",
    "topics.technology": "Technology",
    "topics.finance": "Finance",
    "topics.health": "Health",
    "topics.politics": "Politics",
    "topics.science": "Science",
    "topics.sports": "Sports",
    "topics.entertainment": "Entertainment",
    "topics.business": "Business",
    "topics.world": "World",

    // Content Types (Main App)
    "content.discover": "Discover",
    "content.news": "Latest",
    "content.gov": "Notice",
    
    // Marketplace Categories
    "marketplace.cars": "Cars",
    "marketplace.parking": "Parking",
    
    // Parking Districts
    "parking.allDistricts": "All Districts",
    "parking.hongKongIsland": "Hong Kong Island",
    "parking.kowloon": "Kowloon",
    "parking.newTerritories": "New Territories",
    
    // Article
    "article.readMore": "Read More",
    "article.back": "Back",
    "article.share": "Share",
    "article.readOriginal": "Read original article",
    "article.aiSummary": "AI Summary",
    "article.fullArticle": "Full Article",
    "article.summary": "Summary",
    "article.keyPoints": "Key Points",
    "article.whyItMatters": "Why It Matters",

    // Search
    "search.placeholder": "Search articles...",
    "search.suggestions": "Suggested searches",
    "search.results": "results for",
    "search.noResults": "No articles found for",
    "search.searching": "Searching...",

    // Discovery
    "discovery.trending": "Trending Now",
    "discovery.recommended": "Recommended for You",
    "discovery.recent": "Recently Added",

    // Topics Feed
    "topics.aiEnhancedFeed": "AI-Enhanced Articles",
    "topics.aiEnhancedDescription": "Articles enhanced with AI analysis and additional research",
    "topics.noAiArticles": "No AI-enhanced articles available",
    "topics.noAiArticlesDescription": "AI-enhanced articles in your selected language are not available yet. Please check back later.",

    // Profile
    "profile.saved": "Saved",
    "profile.history": "History",
    "profile.settings": "Settings",
    "profile.savedArticles": "Saved Articles",
    "profile.readingHistory": "Reading History",
    "profile.appearance": "Appearance",
    "profile.darkMode": "Dark Mode",
    "profile.fontSize": "Font Size",
    "profile.notifications": "Notifications",
    "profile.pushNotifications": "Push Notifications",
    "profile.signOut": "Sign Out",
    "profile.language": "Language",

    // Font sizes
    "fontSize.small": "Small",
    "fontSize.medium": "Medium",
    "fontSize.large": "Large",

    // Languages
    "language.en": "English",
    "language.zh-CN": "简体中文",
    "language.zh-TW": "繁體中文",

    // Time
    "time.ago": "ago",
    "time.minute": "minute",
    "time.minutes": "minutes",
    "time.hour": "hour",
    "time.hours": "hours",
    "time.day": "day",
    "time.days": "days",

    // Journey Time
    "journey.title": "Journey Times",
    "journey.subtitle": "Real-time traffic conditions and journey times across Hong Kong",
    "journey.roadType": "Road Type",
    "journey.expressway": "Expressway",
    "journey.trunk": "Major Road",
    "journey.local": "Local Road",
    "journey.temp": "Temporary",
    "journey.enabled": "Enabled",
    "journey.available": "Available",
    "journey.notAvailable": "Not available",
    "journey.notAvailableForRoute": "Not available for this route",
    "journey.noRoutes": "No routes available for selected road types",
    "journey.noData": "No journey time data available",
    "journey.tryDifferent": "Try enabling different road types or selecting different regions",
    "journey.lastUpdated": "Last updated:",
    "journey.dataStale": "Data may be stale",
    "journey.errorLoading": "Error loading journey time data",
    "journey.tryAgain": "Try Again",
    "journey.min": "min",
    "journey.faster": "faster",
    "journey.slower": "slower",
    "journey.route": "Route",
    "journey.updatedAt": "Updated at",
    "journey.thanUsual": "than usual",
    "regions.hk": "Hong Kong Island",
    "regions.kln": "Kowloon",
    "regions.nt": "New Territories",

    // Loading and errors
    loading: "Loading...",
    "error.failedToLoad": "Failed to load",
    "error.articleNotFound": "Article not found",
    "error.failedToFetch": "Failed to fetch",

    // Category Menu
    "categories.selectCategory": "Select Category",
    "categories.roads.label": "Roads",
    "categories.roads.description": "Traffic & journey times",
    "categories.park.label": "Park",
    "categories.park.description": "Parks & recreation",
    "categories.police.label": "Police",
    "categories.police.description": "Police stations & services",
    "categories.ae.label": "A&E",
    "categories.ae.description": "Hospital wait times",
    "categories.weather.label": "Weather",
    "categories.weather.description": "Current & forecast",
    "categories.postbox.label": "Postbox",
    "categories.postbox.description": "Postal services",
    "categories.trashbin.label": "Trashbin",
    "categories.trashbin.description": "Waste management",
    "categories.comingSoon": "Coming Soon",

    // A&E Hospital List
    "ae.hospitals": "Hospitals",
    "ae.withData": "With Data",
    "ae.longWait": "Long Wait",
    "ae.emergencyServices": "Emergency Services",
    "ae.realTimeStatus": "Real-time waiting times across Hong Kong",
    "ae.shortWait": "Short Wait",
    "ae.moderateWait": "Moderate Wait",
    "ae.unavailable": "Unavailable",
    "ae.hour": "hr",
    "ae.hours": "hrs",
    "ae.loading": "Loading...",
    "ae.stale": "Stale",
    "ae.showFilters": "Show Filters",
    "ae.hideFilters": "Hide Filters",
    "ae.clear": "Clear",
    "ae.searchPlaceholder": "Search hospitals...",
    "ae.allClusters": "All Clusters",
    "ae.allTypes": "All Types",
    "ae.waitTime": "Wait Time",
    "ae.currentWaitTime": "Current Wait Time",
    "ae.type": "Type",
    "ae.cluster": "Cluster",
    "ae.address": "Address",
    "ae.phone": "Phone",
    "ae.waitTimeInfo": "Wait Time Information",
    "ae.lastUpdated": "Last updated",
    "ae.unknown": "Unknown",
    "ae.estimateDisclaimer": "Wait times are estimates and may vary",
    "ae.feeInformation": "A&E Fee Information",
    "ae.publicHospital": "Public Hospital (HA)",
    "ae.privateHospital": "Private Hospital",
    "ae.standardFee": "Standard Fee",
    "ae.timeBasedFee": "Time-based Fee",
    "ae.hkd": "HK$",
    "ae.errorLoading": "Error loading A&E data",
    "ae.tryAgain": "Try Again",
    "ae.noData": "No A&E data available",
    "ae.noMatches": "No hospitals match your filters",
    "ae.public": "Public",
    "ae.private": "Private",

    // Police
    "police.policeStations": "Police Stations",
    "police.findStations": "Find police stations and services",
    "police.totalStations": "Total Stations",
    "police.withDirections": "With Directions",
    "police.districts": "Districts",
    "police.serviceTypes": "Service Types",
    "police.allDistricts": "All Districts",
    "police.allServices": "All Services",
    "police.searchPlaceholder": "Search stations...",
    "police.showFilters": "Show Filters",
    "police.hideFilters": "Hide Filters",
    "police.clear": "Clear",
    "police.servicesAvailable": "Services Available",
    "police.address": "Address",
    "police.phone": "Phone",
    "police.coordinatesUnavailable": "Exact coordinates not available for this station",
    "police.call": "Call",
    "police.callStation": "Call Station",
    "police.directions": "Directions",
    "police.search": "Search",
    "police.service": "service",
    "police.services": "services",
    "police.noStations": "No police stations found",
    "police.noMatches": "No stations match your search",
    "police.errorLoading": "Error loading police stations",
    "police.tryAgain": "Try Again",
    "police.loaded": "Loaded",

    // Police Districts
    "district.Hong Kong Island": "Hong Kong Island",
    "district.Kowloon East": "Kowloon East",
    "district.Kowloon West": "Kowloon West",
    "district.Marine Region": "Marine Region",
    "district.New Territories North": "New Territories North",
    "district.New Territories South": "New Territories South",

    // Police Services
    "service.Control Point Police Reporting Centre": "Control Point Police Reporting Centre",
    "service.Police Post": "Police Post",
    "service.Police Reporting Centre": "Police Reporting Centre",
    "service.Police Services Centre": "Police Services Centre",
    "service.Report Room": "Report Room",

    // Police Station Names
    "station.Airport District": "Airport District",
    "station.Ap Lei Chau Division": "Ap Lei Chau Division",
    "station.Central District": "Central District",
    "station.Cheung Chau Division": "Cheung Chau Division",
    "station.Cheung Sha Wan Division": "Cheung Sha Wan Division",
    "station.Choi Hung Division": "Choi Hung Division",
    "station.Eastern District": "Eastern District",
    "station.Fo Tan Division": "Fo Tan Division",
    "station.Heung Yuen Wai Boundary Control Point Police Reporting Centre": "Heung Yuen Wai Boundary Control Point Police Reporting Centre",
    "station.Kai Tak Cruise Terminal Police Reporting Centre": "Kai Tak Cruise Terminal Police Reporting Centre",
    "station.Kam Tin Division": "Kam Tin Division",
    "station.Kowloon Bay Division": "Kowloon Bay Division",
    "station.Kowloon City Division": "Kowloon City Division",
    "station.Kwai Chung Division": "Kwai Chung Division",
    "station.Kwun Tong Division": "Kwun Tong Division",
    "station.Lamma Island Police Post": "Lamma Island Police Post",
    "station.Lo Wu Control Point": "Lo Wu Control Point",
    "station.Lok Ma Chau Boundary Control Point": "Lok Ma Chau Boundary Control Point",
    "station.Ma On Shan Division": "Ma On Shan Division",
    "station.Ma Tau Wai Division": "Ma Tau Wai Division",
    "station.Man Kam To Boundary Control Point": "Man Kam To Boundary Control Point",
    "station.Marine East Division": "Marine East Division",
    "station.Marine North Division": "Marine North Division",
    "station.Marine South Division": "Marine South Division",
    "station.Marine West Division": "Marine West Division",
    "station.Mong Kok Division": "Mong Kok Division",
    "station.Ngau Tau Kok Division": "Ngau Tau Kok Division",
    "station.North Point Division": "North Point Division",
    "station.Peng Chau Police Post": "Peng Chau Police Post",
    "station.Police Services Centre, Central District": "Police Services Centre, Central District",
    "station.Sai Kung Division": "Sai Kung Division",
    "station.Sha Tin Division": "Sha Tin Division",
    "station.Sham Shui Po Division": "Sham Shui Po Division",
    "station.Shatin Pass Division": "Shatin Pass Division",
    "station.Shek Kip Mei Division": "Shek Kip Mei Division",
    "station.Shenzhen Bay Port Reporting Centre": "Shenzhen Bay Port Reporting Centre",
    "station.Southern District": "Southern District",
    "station.Tai Hang Division": "Tai Hang Division",
    "station.Tai Po Division": "Tai Po Division",
    "station.Tai Wai Division": "Tai Wai Division",
    "station.Tin Shui Wai Division": "Tin Shui Wai Division",
    "station.Tsing Yi Division": "Tsing Yi Division",
    "station.Tsuen Wan Division": "Tsuen Wan Division",
    "station.Tuen Mun Division": "Tuen Mun Division",
    "station.Tung Chung Division": "Tung Chung Division",
    "station.Wan Chai Division": "Wan Chai Division",
    "station.West Kowloon Division": "West Kowloon Division",
    "station.Wong Tai Sin Division": "Wong Tai Sin Division",
    "station.Yau Ma Tei Division": "Yau Ma Tei Division",
    "station.Yau Tsim Division": "Yau Tsim Division",
    "station.Yuen Long Division": "Yuen Long Division",

    // Parks
    "parks.parksAndRecreation": "Parks & Recreation",
    "parks.findParks": "Find parks and recreational areas",
    "parks.totalParks": "Total Parks",
    "parks.withDirections": "With Directions",
    "parks.districts": "Districts",
    "parks.parkTypes": "Park Types",
    "parks.allDistricts": "All Districts",
    "parks.allTypes": "All Types",
    "parks.searchPlaceholder": "Search parks...",
    "parks.showFilters": "Show Filters",
    "parks.hideFilters": "Hide Filters",
    "parks.clear": "Clear",
    "parks.parkType": "Park Type",
    "parks.address": "Address",
    "parks.coordinatesUnavailable": "Exact coordinates not available for this park",
    "parks.directions": "Directions",
    "parks.search": "Search",
    "parks.noParks": "No parks found",
    "parks.noMatches": "No parks match your search",
    "parks.errorLoading": "Error loading parks",
    "parks.tryAgain": "Try Again",
    "parks.loaded": "Loaded",
    "parks.addressOnly": "Address Only",

    // Park Districts
    "parkDistrict.hong_kong_island": "Hong Kong Island",
    "parkDistrict.kowloon_east": "Kowloon East",
    "parkDistrict.kowloon_west": "Kowloon West",
    "parkDistrict.new_territories_north": "New Territories North",
    "parkDistrict.new_territories_south": "New Territories South",
    "parkDistrict.islands": "Islands",
    "parkDistrict.other": "Other",

    // Park Types
    "parkType.public_park": "Public Park",
    "parkType.country_park": "Country Park",
    "parkType.beach_park": "Beach Park",
    "parkType.garden": "Garden",
    "parkType.recreation_ground": "Recreation Ground",
    "parkType.playground": "Playground",
    "parkType.sports_ground": "Sports Ground",
    "parkType.swimming_pool": "Swimming Pool",
    "parkType.waterfront_park": "Waterfront Park",

    // Hospital Names
    "hospital.AHNH": "Alice Ho Miu Ling Nethersole Hospital",
    "hospital.CGH": "Caritas Medical Centre",
    "hospital.KWH": "Kwong Wah Hospital",
    "hospital.PMH": "Princess Margaret Hospital",
    "hospital.QEH": "Queen Elizabeth Hospital",
    "hospital.QMH": "Queen Mary Hospital",
    "hospital.RHTSK": "Ruttonjee Hospital",
    "hospital.TMH": "Tuen Mun Hospital",
    "hospital.UCH": "United Christian Hospital",
    "hospital.WWH": "Yan Chai Hospital",
    "hospital.PYNEH": "Pamela Youde Nethersole Eastern Hospital",
    "hospital.TKOH": "Tseung Kwan O Hospital",
    "hospital.NLTH": "North Lantau Hospital",
    "hospital.HKEH": "Hong Kong Eye Hospital",
    "hospital.NDH": "North District Hospital",
    "hospital.PWH": "Prince of Wales Hospital",
    "hospital.TSH": "Tin Shui Wai Hospital",
    "hospital.POH": "Pok Oi Hospital",
    "hospital.SJH": "St. John Hospital",
    "hospital.HKBH": "Hong Kong Baptist Hospital",
    "hospital.HKSH": "Hong Kong Sanatorium & Hospital",

    // Hospital Addresses
    "address.AHNH": "11 Chuen On Road, Tai Po, New Territories",
    "address.CGH": "111 Wing Hong Street, Sham Shui Po, Kowloon",
    "address.KWH": "25 Waterloo Road, Yau Ma Tei, Kowloon",
    "address.PMH": "2-10 Princess Margaret Hospital Road, Lai Chi Kok, Kowloon",
    "address.QEH": "30 Gascoigne Road, Yau Ma Tei, Kowloon",
    "address.QMH": "102 Pokfulam Road, Pokfulam, Hong Kong",
    "address.RHTSK": "266 Queen's Road East, Wan Chai, Hong Kong",
    "address.TMH": "23 Tsing Chung Koon Road, Tuen Mun, New Territories",
    "address.UCH": "130 Hip Wo Street, Kwun Tong, Kowloon",
    "address.WWH": "7-29 Yan Chai Street, Tsuen Wan, New Territories",
    "address.PYNEH": "3 Lok Man Road, Chai Wan, Hong Kong",
    "address.TKOH": "2 Po Ning Lane, Hang Hau, Tseung Kwan O, New Territories",
    "address.NLTH": "8 Chek Lap Kok South Road, Lantau Island, New Territories",
    "address.HKEH": "147K Argyle Street, Mong Kok, Kowloon",
    "address.NDH": "9 Po Kin Road, Sheung Shui, New Territories",
    "address.PWH": "30-32 Ngan Shing Street, Sha Tin, New Territories",
    "address.TSH": "2 Tin Tan Street, Tin Shui Wai, New Territories",
    "address.POH": "99 Tsing Yang Street, Tsuen Wan, New Territories",
    "address.SJH": "2 MacDonnell Road, Mid-Levels, Hong Kong",
    "address.HKBH": "222 Waterloo Road, Kowloon Tong, Kowloon",
    "address.HKSH": "2 Village Road, Happy Valley, Hong Kong",

    // District Clusters
    "cluster.hongKongEast": "Hong Kong East",
    "cluster.hongKongWest": "Hong Kong West",
    "cluster.kowloonCentral": "Kowloon Central",
    "cluster.kowloonEast": "Kowloon East",
    "cluster.kowloonWest": "Kowloon West",
    "cluster.newTerritoriesEast": "New Territories East",
    "cluster.newTerritoriesWest": "New Territories West",

    // Authentication
    "auth.createAccount": "Create account",
    "auth.joinCommunity": "Join our community to get started",
    "auth.signIn": "Sign in",
    "auth.welcomeBack": "Welcome back",
    "auth.username": "Username",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.createAccountButton": "Create Account",
    "auth.signInButton": "Sign In",
    "auth.creatingAccount": "Creating account...",
    "auth.signingIn": "Signing in...",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.signInHere": "Sign in here",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.createOne": "Create one",
    "auth.accountCreated": "Account created successfully! Please check your email to verify your account.",
    "auth.invalidCredentials": "Invalid login credentials",
    "auth.usernameTaken": "Username is already taken",
    "auth.usernameAvailable": "Username is available!",
    "auth.checkingAvailability": "Checking availability...",
    "auth.usernameInvalid": "Username must start with @ and contain only letters, numbers, and underscores (4-20 characters)",
    "auth.chooseUsername": "Choose a unique username starting with @",
    "auth.fillAllFields": "Please fill in all fields",
    "auth.enterValidUsername": "Please enter a valid username",
    "auth.chooseAvailableUsername": "Please choose an available username",
    "auth.enterValidEmail": "Please enter a valid email address",
    "auth.passwordTooShort": "Password must be at least 6 characters long",
    "auth.passwordsDontMatch": "Passwords do not match",
    "auth.passwordMinLength": "Must be at least 6 characters long",
    "auth.enterEmail": "Enter your email",
    "auth.enterPassword": "Enter your password",
    "auth.createPassword": "Create a password",
    "auth.confirmYourPassword": "Confirm your password",
    "auth.signInRequired": "Sign in required",
    "auth.signInToBookmark": "Please sign in to bookmark articles for later reading.",
    "auth.needAccount": "Need an account?",
    "auth.haveAccount": "Already have an account?",

    // Menu
    "menu.title": "Menu",
    "menu.signIn": "Sign In",
    "menu.signUp": "Sign Up",
    "menu.settingsInfo": "Settings and information",
    "menu.enterDetails": "Enter your details below",
    "menu.account": "Account",
    "menu.systemStatus": "System Status",
    "menu.theme": "Theme",
    "menu.loading": "Loading...",
    "menu.backToMenu": "Back to menu",
    "menu.closeMenu": "Close menu",

    // Real-time updates
    "realtime.active": "Real-time updates active",
    "realtime.connecting": "Connecting to real-time updates...",

    // Bookmarks Empty State
    "bookmarks.emptyState.title": "Your reading list awaits",
    "bookmarks.emptyState.description": "Save articles that matter to you.\nRead them anytime, anywhere.",
    
    // Bookmarks Search
    "bookmarks.search.placeholder": "Search bookmarks...",
    "bookmarks.search.noResults": "No bookmarks found",
    "bookmarks.search.noResultsDesc": "No bookmarks match \"{query}\". Try a different search term.",
    "bookmarks.search.clearSearch": "Clear search",

    // Filter Categories
    "filters.all": "All",
    "filters.hkma": "HKMA",
    "filters.gov": "Gov",
    "filters.road": "Road",
    "filters.transport": "Transport",
    "filters.weather": "Weather",
    "filters.health": "Health",
    "filters.hospital": "Hospital",
    "filters.utility": "Utility",
    "filters.rail": "Rail",
    "filters.police": "Police",
    "filters.emergency": "Emergency",
    "filters.education": "Education",
    "filters.immigration": "Immigration",
    "filters.environment": "Environment",

    // Bulletin
    "bulletin.noContent": "Content not yet available",
    "bulletin.readMore": "Read more",
    "bulletin.viewOriginal": "View original",

    // News Outlets
    "outlets.allSources": "All Sources",
    "outlets.Bloomberg": "Bloomberg",
    "outlets.SCMP": "SCMP",
    "outlets.HKFP": "HKFP",
    "outlets.RTHK": "RTHK",
    "outlets.HK01": "HK01",
    "outlets.TVB": "TVB",
    "outlets.AM730": "AM730",
    "outlets.HKEJ": "HKEJ",
    "outlets.On.cc": "On.cc",
    "outlets.SingTao": "SingTao",
    "outlets.Ming Pao": "Ming Pao",
    "outlets.Oriental Daily": "Oriental Daily",
    "outlets.The Standard": "The Standard",
    "outlets.Now News": "Now News",
    "outlets.InMedia": "InMedia",
    "outlets.Coconuts Hong Kong": "Coconuts Hong Kong",
    "outlets.Hong Kong Government News": "Hong Kong Government News",
    "outlets.Bastille Post": "Bastille Post",
    "outlets.Metro Radio": "Metro Radio",
    "outlets.Commercial Radio": "Commercial Radio",
  },
  "zh-CN": {
    // Header
    "app.title": "秒知",
    "nav.search": "搜索",

    // Navigation
    "nav.home": "首页",
    "nav.topics": "话题",
    "nav.bookmarks": "书签",
    "nav.profile": "个人",

    // Topics
    "topics.all": "全部",
    "topics.technology": "科技",
    "topics.finance": "金融",
    "topics.health": "健康",
    "topics.politics": "政治",
    "topics.science": "科学",
    "topics.sports": "体育",
    "topics.entertainment": "娱乐",
    "topics.business": "商业",
    "topics.world": "国际",
    
    // Content Types (Main App)
    "content.discover": "要闻",
    "content.news": "最新",
    "content.gov": "通告",
    
    // Marketplace Categories
    "marketplace.cars": "汽车",
    "marketplace.parking": "停车",
    
    // Parking Districts
    "parking.allDistricts": "所有地区",
    "parking.hongKongIsland": "香港岛",
    "parking.kowloon": "九龙",
    "parking.newTerritories": "新界",

    // Article
    "article.readMore": "阅读更多",
    "article.back": "返回",
    "article.share": "分享",
    "article.readOriginal": "阅读原文",
    "article.aiSummary": "AI 摘要",
    "article.fullArticle": "完整文章",
    "article.summary": "摘要",
    "article.keyPoints": "要点",
    "article.whyItMatters": "为什么重要",

    // Search
    "search.placeholder": "搜索文章...",
    "search.suggestions": "推荐搜索",
    "search.results": "个结果",
    "search.noResults": "未找到相关文章",
    "search.searching": "搜索中...",

    // Discovery
    "discovery.trending": "热门话题",
    "discovery.recommended": "为您推荐",
    "discovery.recent": "最新添加",

    // Topics Feed
    "topics.aiEnhancedFeed": "AI 增强文章",
    "topics.aiEnhancedDescription": "通过 AI 分析和额外研究增强的文章",
    "topics.noAiArticles": "暂无 AI 增强文章",
    "topics.noAiArticlesDescription": "您选择的语言暂时没有 AI 增强文章。请稍后再试。",

    // Profile
    "profile.saved": "收藏",
    "profile.history": "历史",
    "profile.settings": "设置",
    "profile.savedArticles": "收藏文章",
    "profile.readingHistory": "阅读历史",
    "profile.appearance": "外观",
    "profile.darkMode": "深色模式",
    "profile.fontSize": "字体大小",
    "profile.notifications": "通知",
    "profile.pushNotifications": "推送通知",
    "profile.signOut": "退出登录",
    "profile.language": "语言",

    // Font sizes
    "fontSize.small": "小",
    "fontSize.medium": "中",
    "fontSize.large": "大",

    // Languages
    "language.en": "English",
    "language.zh-CN": "简体中文",
    "language.zh-TW": "繁體中文",

    // Time
    "time.ago": "前",
    "time.minute": "分钟",
    "time.minutes": "分钟",
    "time.hour": "小时",
    "time.hours": "小时",
    "time.day": "天",
    "time.days": "天",

    // Journey Time
    "journey.title": "行程时间",
    "journey.subtitle": "香港实时交通状况和行程时间",
    "journey.roadType": "道路类型",
    "journey.expressway": "高速公路",
    "journey.trunk": "主要道路",
    "journey.local": "本地道路",
    "journey.temp": "临时路线",
    "journey.enabled": "已启用",
    "journey.available": "可用",
    "journey.notAvailable": "不可用",
    "journey.notAvailableForRoute": "此路线不可用",
    "journey.noRoutes": "所选道路类型无可用路线",
    "journey.noData": "无行程时间数据",
    "journey.tryDifferent": "请尝试启用不同的道路类型或选择不同的地区",
    "journey.lastUpdated": "最后更新：",
    "journey.dataStale": "数据可能过时",
    "journey.errorLoading": "加载行程时间数据时出错",
    "journey.tryAgain": "重试",
    "journey.min": "分钟",
    "journey.faster": "更快",
    "journey.slower": "更慢",
    "journey.route": "路线",
    "journey.updatedAt": "更新于",
    "journey.thanUsual": "比平常",
    "regions.hk": "香港岛",
    "regions.kln": "九龙",
    "regions.nt": "新界",

    // Loading and errors
    loading: "加载中...",
    "error.failedToLoad": "加载失败",
    "error.articleNotFound": "文章未找到",
    "error.failedToFetch": "获取失败",

    // Category Menu
    "categories.selectCategory": "选择分类",
    "categories.roads.label": "道路",
    "categories.roads.description": "交通与行程时间",
    "categories.park.label": "公园",
    "categories.park.description": "公园与娱乐",
    "categories.police.label": "警察",
    "categories.police.description": "警察局与服务",
    "categories.ae.label": "急诊科",
    "categories.ae.description": "医院等候时间",
    "categories.weather.label": "天气",
    "categories.weather.description": "当前与预报",
    "categories.postbox.label": "邮箱",
    "categories.postbox.description": "邮政服务",
    "categories.trashbin.label": "垃圾桶",
    "categories.trashbin.description": "废物管理",
    "categories.comingSoon": "即将推出",

    // A&E Hospital List
    "ae.hospitals": "医院",
    "ae.withData": "有数据",
    "ae.longWait": "长等待",
    "ae.emergencyServices": "急诊服务",
    "ae.realTimeStatus": "香港实时等待时间",
    "ae.shortWait": "短等待",
    "ae.moderateWait": "中等待",
    "ae.unavailable": "不可用",
    "ae.hour": "小时",
    "ae.hours": "小时",
    "ae.loading": "加载中...",
    "ae.stale": "过时",
    "ae.showFilters": "显示筛选",
    "ae.hideFilters": "隐藏筛选",
    "ae.clear": "清除",
    "ae.searchPlaceholder": "搜索医院...",
    "ae.allClusters": "所有医院群",
    "ae.allTypes": "所有类型",
    "ae.waitTime": "等待时间",
    "ae.currentWaitTime": "当前等待时间",
    "ae.type": "类型",
    "ae.cluster": "医院群",
    "ae.address": "地址",
    "ae.phone": "电话",
    "ae.waitTimeInfo": "等待时间信息",
    "ae.lastUpdated": "最后更新",
    "ae.unknown": "未知",
    "ae.estimateDisclaimer": "等待时间为估算值，可能会有所变化",
    "ae.feeInformation": "急诊科收费信息",
    "ae.publicHospital": "公立医院（醫管局）",
    "ae.privateHospital": "私立医院",
    "ae.standardFee": "标准收费",
    "ae.timeBasedFee": "分时收费",
    "ae.hkd": "港元",
    "ae.errorLoading": "加载急诊科数据失败",
    "ae.tryAgain": "重试",
    "ae.noData": "没有急诊科数据",
    "ae.noMatches": "没有医院符合您的筛选条件",
    "ae.public": "公立",
    "ae.private": "私立",

    // Police (Simplified Chinese)
    "police.policeStations": "警察局",
    "police.findStations": "查找警察局和服务",
    "police.totalStations": "总计警察局",
    "police.withDirections": "可导航",
    "police.districts": "区域",
    "police.serviceTypes": "服务类型",
    "police.allDistricts": "所有区域",
    "police.allServices": "所有服务",
    "police.searchPlaceholder": "搜索警察局...",
    "police.showFilters": "显示筛选",
    "police.hideFilters": "隐藏筛选",
    "police.clear": "清除",
    "police.servicesAvailable": "提供服务",
    "police.address": "地址",
    "police.phone": "电话",
    "police.coordinatesUnavailable": "此警察局无确切坐标",
    "police.call": "呼叫",
    "police.callStation": "呼叫警察局",
    "police.directions": "导航",
    "police.search": "搜索",
    "police.service": "项服务",
    "police.services": "项服务",
    "police.noStations": "未找到警察局",
    "police.noMatches": "没有警察局符合您的搜索",
    "police.errorLoading": "加载警察局数据失败",
    "police.tryAgain": "重试",
    "police.loaded": "已加载",

    // Police Districts (Simplified Chinese)
    "district.Hong Kong Island": "香港岛",
    "district.Kowloon East": "九龙东",
    "district.Kowloon West": "九龙西",
    "district.Marine Region": "水警区",
    "district.New Territories North": "新界北",
    "district.New Territories South": "新界南",

    // Police Services (Simplified Chinese)
    "service.Control Point Police Reporting Centre": "管制站警务报案中心",
    "service.Police Post": "警岗",
    "service.Police Reporting Centre": "警务报案中心",
    "service.Police Services Centre": "警务服务中心",
    "service.Report Room": "报案室",

    // Police Station Names (Simplified Chinese)
    "station.Airport District": "机场区",
    "station.Ap Lei Chau Division": "鸭脷洲分区",
    "station.Central District": "中区",
    "station.Cheung Chau Division": "长洲分区",
    "station.Cheung Sha Wan Division": "长沙湾分区",
    "station.Choi Hung Division": "彩虹分区",
    "station.Eastern District": "东区",
    "station.Fo Tan Division": "火炭分区",
    "station.Heung Yuen Wai Boundary Control Point Police Reporting Centre": "香园围边界管制站警务报案中心",
    "station.Kai Tak Cruise Terminal Police Reporting Centre": "启德邮轮码头警务报案中心",
    "station.Kam Tin Division": "锦田分区",
    "station.Kowloon Bay Division": "九龙湾分区",
    "station.Kowloon City Division": "九龙城分区",
    "station.Kwai Chung Division": "葵涌分区",
    "station.Kwun Tong Division": "观塘分区",
    "station.Lamma Island Police Post": "南丫岛警岗",
    "station.Lo Wu Control Point": "罗湖管制站",
    "station.Lok Ma Chau Boundary Control Point": "落马洲边界管制站",
    "station.Ma On Shan Division": "马鞍山分区",
    "station.Ma Tau Wai Division": "马头围分区",
    "station.Man Kam To Boundary Control Point": "文锦渡边界管制站",
    "station.Marine East Division": "水警东分区",
    "station.Marine North Division": "水警北分区",
    "station.Marine South Division": "水警南分区",
    "station.Marine West Division": "水警西分区",
    "station.Mong Kok Division": "旺角分区",
    "station.Ngau Tau Kok Division": "牛头角分区",
    "station.North Point Division": "北角分区",
    "station.Peng Chau Police Post": "坪洲警岗",
    "station.Police Services Centre, Central District": "警务服务中心，中区",
    "station.Sai Kung Division": "西贡分区",
    "station.Sha Tin Division": "沙田分区",
    "station.Sham Shui Po Division": "深水埗分区",
    "station.Shatin Pass Division": "沙田坳分区",
    "station.Shek Kip Mei Division": "石硖尾分区",
    "station.Shenzhen Bay Port Reporting Centre": "深圳湾口岸报案中心",
    "station.Southern District": "南区",
    "station.Tai Hang Division": "大坑分区",
    "station.Tai Po Division": "大埔分区",
    "station.Tai Wai Division": "大围分区",
    "station.Tin Shui Wai Division": "天水围分区",
    "station.Tsing Yi Division": "青衣分区",
    "station.Tsuen Wan Division": "荃湾分区",
    "station.Tuen Mun Division": "屯门分区",
    "station.Tung Chung Division": "东涌分区",
    "station.Wan Chai Division": "湾仔分区",
    "station.West Kowloon Division": "西九龙分区",
    "station.Wong Tai Sin Division": "黄大仙分区",
    "station.Yau Ma Tei Division": "油麻地分区",
    "station.Yau Tsim Division": "油尖分区",
    "station.Yuen Long Division": "元朗分区",

    // Parks (Simplified Chinese)
    "parks.parksAndRecreation": "公园与娱乐",
    "parks.findParks": "查找公园和休闲区",
    "parks.totalParks": "总计公园",
    "parks.withDirections": "可导航",
    "parks.districts": "区域",
    "parks.parkTypes": "公园类型",
    "parks.allDistricts": "所有区域",
    "parks.allTypes": "所有类型",
    "parks.searchPlaceholder": "搜索公园...",
    "parks.showFilters": "显示筛选",
    "parks.hideFilters": "隐藏筛选",
    "parks.clear": "清除",
    "parks.parkType": "公园类型",
    "parks.address": "地址",
    "parks.coordinatesUnavailable": "此公园无确切坐标",
    "parks.directions": "导航",
    "parks.search": "搜索",
    "parks.noParks": "未找到公园",
    "parks.noMatches": "没有公园符合您的搜索",
    "parks.errorLoading": "加载公园数据失败",
    "parks.tryAgain": "重试",
    "parks.loaded": "已加载",
    "parks.addressOnly": "仅地址",

    // Park Districts (Simplified Chinese)
    "parkDistrict.hong_kong_island": "香港岛",
    "parkDistrict.kowloon_east": "九龙东",
    "parkDistrict.kowloon_west": "九龙西",
    "parkDistrict.new_territories_north": "新界北",
    "parkDistrict.new_territories_south": "新界南",
    "parkDistrict.islands": "离岛",
    "parkDistrict.other": "其他",

    // Park Types (Simplified Chinese)
    "parkType.public_park": "公共公园",
    "parkType.country_park": "郊野公园",
    "parkType.beach_park": "海滨公园",
    "parkType.garden": "花园",
    "parkType.recreation_ground": "游乐场",
    "parkType.playground": "儿童游乐场",
    "parkType.sports_ground": "体育场",
    "parkType.swimming_pool": "游泳池",
    "parkType.waterfront_park": "海滨公园",

    // Hospital Names (Simplified Chinese)
    "hospital.AHNH": "雅丽氏何妙龄那打素医院",
    "hospital.CGH": "明爱医院",
    "hospital.KWH": "广华医院",
    "hospital.PMH": "玛嘉烈医院",
    "hospital.QEH": "伊利沙白医院",
    "hospital.QMH": "玛丽医院",
    "hospital.RHTSK": "律敦治医院",
    "hospital.TMH": "屯门医院",
    "hospital.UCH": "基督教联合医院",
    "hospital.WWH": "仁济医院",
    "hospital.PYNEH": "东区尤德夫人那打素医院",
    "hospital.TKOH": "将军澳医院",
    "hospital.NLTH": "北大屿山医院",
    "hospital.HKEH": "香港眼科医院",
    "hospital.NDH": "北区医院",
    "hospital.PWH": "威尔斯亲王医院",
    "hospital.TSH": "天水围医院",
    "hospital.POH": "博爱医院",
    "hospital.SJH": "圣约翰医院",
    "hospital.HKBH": "香港浸信会医院",
    "hospital.HKSH": "香港养和医院",

    // Hospital Addresses (Simplified Chinese)
    "address.AHNH": "新界大埔全安路11号",
    "address.CGH": "九龙深水埗永康街111号",
    "address.KWH": "九龙油麻地窦打老道25号",
    "address.PMH": "九龙荔枝角玛嘉烈医院道2-10号",
    "address.QEH": "九龙油麻地加斯科尼道30号",
    "address.QMH": "香港薨美薨美道102号",
    "address.RHTSK": "香港湾仔皇后大道东266号",
    "address.TMH": "新界屯门青松观路23号",
    "address.UCH": "九龙观塘協和街130号",
    "address.WWH": "新界荿湾仁济街7-29号",
    "address.PYNEH": "香港柴湾乐民道3号",
    "address.TKOH": "新界将军澳坑口宝宁里2号",
    "address.NLTH": "新界大屿山赤鳛角南路8号",
    "address.HKEH": "九龙旺角亚皮路147K号",
    "address.NDH": "新界上水保健路9号",
    "address.PWH": "新界沙田银城街30-32号",
    "address.TSH": "新界天水围天坛街2号",
    "address.POH": "新界荿湾青山公路99号",
    "address.SJH": "香港半山区麦当劳道2号",
    "address.HKBH": "九龙九龙塘窦打老道222号",
    "address.HKSH": "香港跑马地山村道2号",

    // District Clusters (Simplified Chinese)
    "cluster.hongKongEast": "香港东区",
    "cluster.hongKongWest": "香港西区",
    "cluster.kowloonCentral": "九龙中区",
    "cluster.kowloonEast": "九龙东区",
    "cluster.kowloonWest": "九龙西区",
    "cluster.newTerritoriesEast": "新界东区",
    "cluster.newTerritoriesWest": "新界西区",

    // Authentication (Simplified Chinese)
    "auth.createAccount": "创建账户",
    "auth.joinCommunity": "加入我们的社区开始使用",
    "auth.signIn": "登录",
    "auth.welcomeBack": "欢迎回来",
    "auth.username": "用户名",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.confirmPassword": "确认密码",
    "auth.createAccountButton": "创建账户",
    "auth.signInButton": "登录",
    "auth.creatingAccount": "创建账户中...",
    "auth.signingIn": "登录中...",
    "auth.alreadyHaveAccount": "已有账户？",
    "auth.signInHere": "点击登录",
    "auth.dontHaveAccount": "没有账户？",
    "auth.createOne": "创建账户",
    "auth.accountCreated": "账户创建成功！请查看邮箱验证您的账户。",
    "auth.invalidCredentials": "登录凭据无效",
    "auth.usernameTaken": "用户名已被占用",
    "auth.usernameAvailable": "用户名可用！",
    "auth.checkingAvailability": "检查可用性中...",
    "auth.usernameInvalid": "用户名必须以@开头，只能包含字母、数字和下划线（4-20个字符）",
    "auth.chooseUsername": "选择一个以@开头的唯一用户名",
    "auth.fillAllFields": "请填写所有字段",
    "auth.enterValidUsername": "请输入有效的用户名",
    "auth.chooseAvailableUsername": "请选择一个可用的用户名",
    "auth.enterValidEmail": "请输入有效的邮箱地址",
    "auth.passwordTooShort": "密码必须至少6个字符",
    "auth.passwordsDontMatch": "密码不匹配",
    "auth.passwordMinLength": "至少6个字符",
    "auth.enterEmail": "输入您的邮箱",
    "auth.enterPassword": "输入您的密码",
    "auth.createPassword": "创建密码",
    "auth.confirmYourPassword": "确认您的密码",
    "auth.signInRequired": "需要登录",
    "auth.signInToBookmark": "请登录以收藏文章供以后阅读。",
    "auth.needAccount": "需要账户？",
    "auth.haveAccount": "已有账户？",

    // Menu (Simplified Chinese)
    "menu.title": "菜单",
    "menu.signIn": "登录",
    "menu.signUp": "注册",
    "menu.settingsInfo": "设置和信息",
    "menu.enterDetails": "请在下方输入您的详细信息",
    "menu.account": "账户",
    "menu.systemStatus": "系统状态",
    "menu.theme": "主题",
    "menu.loading": "加载中...",
    "menu.backToMenu": "返回菜单",
    "menu.closeMenu": "关闭菜单",

    // Real-time updates
    "realtime.active": "实时更新已启动",
    "realtime.connecting": "正在连接实时更新...",

    // Bookmarks Empty State
    "bookmarks.emptyState.title": "您的阅读清单正在等待",
    "bookmarks.emptyState.description": "保存对您重要的文章。\n随时随地阅读。",
    
    // Bookmarks Search
    "bookmarks.search.placeholder": "搜索书签...",
    "bookmarks.search.noResults": "未找到书签",
    "bookmarks.search.noResultsDesc": "没有书签匹配 \"{query}\"。请尝试其他搜索词。",
    "bookmarks.search.clearSearch": "清除搜索",

    // Filter Categories
    "filters.all": "全部",
    "filters.hkma": "金管局",
    "filters.gov": "政府",
    "filters.road": "道路",
    "filters.transport": "交通",
    "filters.weather": "天气",
    "filters.health": "健康",
    "filters.hospital": "医院",
    "filters.utility": "公用",
    "filters.rail": "铁路",
    "filters.police": "警察",
    "filters.emergency": "紧急",
    "filters.education": "教育",
    "filters.immigration": "移民",
    "filters.environment": "环境",

    // Bulletin
    "bulletin.noContent": "内容尚未可用",
    "bulletin.readMore": "阅读更多",
    "bulletin.viewOriginal": "查看原文",

    // News Outlets
    "outlets.allSources": "所有来源",
    "outlets.Bloomberg": "彭博社",
    "outlets.SCMP": "南华早报",
    "outlets.HKFP": "香港自由新闻",
    "outlets.RTHK": "香港电台",
    "outlets.HK01": "香港01",
    "outlets.TVB": "无线电视",
    "outlets.AM730": "AM730",
    "outlets.HKEJ": "信报财经新闻",
    "outlets.On.cc": "东网",
    "outlets.SingTao": "星岛日报",
    "outlets.Ming Pao": "明报",
    "outlets.Oriental Daily": "东方日报",
    "outlets.The Standard": "英文虎报",
    "outlets.Now News": "Now新闻",
    "outlets.InMedia": "香港独立媒体",
    "outlets.Coconuts Hong Kong": "椰子香港",
    "outlets.Hong Kong Government News": "香港政府新闻",
    "outlets.Bastille Post": "巴士的报",
    "outlets.Metro Radio": "新城电台",
    "outlets.Commercial Radio": "商业电台",
  },
  "zh-TW": {
    // Header
    "app.title": "秒知",
    "nav.search": "搜尋",

    // Navigation
    "nav.home": "首頁",
    "nav.topics": "話題",
    "nav.bookmarks": "書籤",
    "nav.profile": "個人",

    // Topics
    "topics.all": "全部",
    "topics.technology": "科技",
    "topics.finance": "金融",
    "topics.health": "健康",
    "topics.politics": "政治",
    "topics.science": "科學",
    "topics.sports": "體育",
    "topics.entertainment": "娛樂",
    "topics.business": "商業",
    "topics.world": "國際",
    
    // Content Types (Main App)
    "content.discover": "要聞",
    "content.news": "最新",
    "content.gov": "通告",
    
    // Marketplace Categories
    "marketplace.cars": "汽車",
    "marketplace.parking": "停車",
    
    // Parking Districts
    "parking.allDistricts": "所有地區",
    "parking.hongKongIsland": "香港島",
    "parking.kowloon": "九龍",
    "parking.newTerritories": "新界",

    // Article
    "article.readMore": "閱讀更多",
    "article.back": "返回",
    "article.share": "分享",
    "article.readOriginal": "閱讀原文",
    "article.aiSummary": "AI 摘要",
    "article.fullArticle": "完整文章",
    "article.summary": "摘要",
    "article.keyPoints": "要點",
    "article.whyItMatters": "為什麼重要",

    // Search
    "search.placeholder": "搜尋文章...",
    "search.suggestions": "推薦搜尋",
    "search.results": "個結果",
    "search.noResults": "未找到相關文章",
    "search.searching": "搜尋中...",

    // Discovery
    "discovery.trending": "熱門話題",
    "discovery.recommended": "為您推薦",
    "discovery.recent": "最新添加",

    // Topics Feed
    "topics.aiEnhancedFeed": "AI 增強文章",
    "topics.aiEnhancedDescription": "通過 AI 分析和額外研究增強的文章",
    "topics.noAiArticles": "暫無 AI 增強文章",
    "topics.noAiArticlesDescription": "您選擇的語言暫時沒有 AI 增強文章。請稍後再試。",

    // Profile
    "profile.saved": "收藏",
    "profile.history": "歷史",
    "profile.settings": "設定",
    "profile.savedArticles": "收藏文章",
    "profile.readingHistory": "閱讀歷史",
    "profile.appearance": "外觀",
    "profile.darkMode": "深色模式",
    "profile.fontSize": "字體大小",
    "profile.notifications": "通知",
    "profile.pushNotifications": "推送通知",
    "profile.signOut": "登出",
    "profile.language": "語言",

    // Font sizes
    "fontSize.small": "小",
    "fontSize.medium": "中",
    "fontSize.large": "大",

    // Languages
    "language.en": "English",
    "language.zh-CN": "简体中文",
    "language.zh-TW": "繁體中文",

    // Time
    "time.ago": "前",
    "time.minute": "分鐘",
    "time.minutes": "分鐘",
    "time.hour": "小時",
    "time.hours": "小時",
    "time.day": "天",
    "time.days": "天",

    // Journey Time
    "journey.title": "行程時間",
    "journey.subtitle": "香港實時交通狀況和行程時間",
    "journey.roadType": "道路類型",
    "journey.expressway": "高速公路",
    "journey.trunk": "主要道路",
    "journey.local": "本地道路",
    "journey.temp": "臨時路線",
    "journey.enabled": "已啟用",
    "journey.available": "可用",
    "journey.notAvailable": "不可用",
    "journey.notAvailableForRoute": "此路線不可用",
    "journey.noRoutes": "所選道路類型無可用路線",
    "journey.noData": "無行程時間數據",
    "journey.tryDifferent": "請嘗試啟用不同的道路類型或選擇不同的地區",
    "journey.lastUpdated": "最後更新：",
    "journey.dataStale": "數據可能過時",
    "journey.errorLoading": "載入行程時間數據時出錯",
    "journey.tryAgain": "重試",
    "journey.min": "分鐘",
    "journey.faster": "更快",
    "journey.slower": "更慢",
    "journey.route": "路線",
    "journey.updatedAt": "更新於",
    "journey.thanUsual": "比平常",
    "regions.hk": "香港島",
    "regions.kln": "九龍",
    "regions.nt": "新界",

    // Loading and errors
    loading: "載入中...",
    "error.failedToLoad": "載入失敗",
    "error.articleNotFound": "文章未找到",
    "error.failedToFetch": "獲取失敗",

    // Category Menu
    "categories.selectCategory": "選擇分類",
    "categories.roads.label": "道路",
    "categories.roads.description": "交通與行程時間",
    "categories.park.label": "公園",
    "categories.park.description": "公園與娛樂",
    "categories.police.label": "警察",
    "categories.police.description": "警察局與服務",
    "categories.ae.label": "急診科",
    "categories.ae.description": "醫院等候時間",
    "categories.weather.label": "天氣",
    "categories.weather.description": "當前與預報",
    "categories.postbox.label": "郵箱",
    "categories.postbox.description": "郵政服務",
    "categories.trashbin.label": "垃圾桶",
    "categories.trashbin.description": "廢物管理",
    "categories.comingSoon": "即將推出",

    // A&E Hospital List
    "ae.hospitals": "醫院",
    "ae.withData": "有數據",
    "ae.longWait": "長等待",
    "ae.emergencyServices": "急診服務",
    "ae.realTimeStatus": "香港實時等待時間",
    "ae.shortWait": "短等待",
    "ae.moderateWait": "中等待",
    "ae.unavailable": "不可用",
    "ae.hour": "小時",
    "ae.hours": "小時",
    "ae.loading": "載入中...",
    "ae.stale": "過時",
    "ae.showFilters": "顯示篩選",
    "ae.hideFilters": "隱藏篩選",
    "ae.clear": "清除",
    "ae.searchPlaceholder": "搜尋醫院...",
    "ae.allClusters": "所有醫院群",
    "ae.allTypes": "所有類型",
    "ae.waitTime": "等待時間",
    "ae.currentWaitTime": "當前等待時間",
    "ae.type": "類型",
    "ae.cluster": "醫院群",
    "ae.address": "地址",
    "ae.phone": "電話",
    "ae.waitTimeInfo": "等待時間資訊",
    "ae.lastUpdated": "最後更新",
    "ae.unknown": "未知",
    "ae.estimateDisclaimer": "等待時間為估算值，可能會有所變化",
    "ae.feeInformation": "急診科收費資訊",
    "ae.publicHospital": "公立醫院（醫管局）",
    "ae.privateHospital": "私立醫院",
    "ae.standardFee": "標準收費",
    "ae.timeBasedFee": "分時收費",
    "ae.hkd": "港元",
    "ae.errorLoading": "載入急診科數據失敗",
    "ae.tryAgain": "重試",
    "ae.noData": "沒有急診科數據",
    "ae.noMatches": "沒有醫院符合您的篩選條件",
    "ae.public": "公立",
    "ae.private": "私立",

    // Police (Traditional Chinese)
    "police.policeStations": "警察局",
    "police.findStations": "查找警察局和服務",
    "police.totalStations": "總計警察局",
    "police.withDirections": "可導航",
    "police.districts": "區域",
    "police.serviceTypes": "服務類型",
    "police.allDistricts": "所有區域",
    "police.allServices": "所有服務",
    "police.searchPlaceholder": "搜索警察局...",
    "police.showFilters": "顯示篩選",
    "police.hideFilters": "隱藏篩選",
    "police.clear": "清除",
    "police.servicesAvailable": "提供服務",
    "police.address": "地址",
    "police.phone": "電話",
    "police.coordinatesUnavailable": "此警察局無確切坐標",
    "police.call": "呼叫",
    "police.callStation": "呼叫警察局",
    "police.directions": "導航",
    "police.search": "搜索",
    "police.service": "項服務",
    "police.services": "項服務",
    "police.noStations": "未找到警察局",
    "police.noMatches": "沒有警察局符合您的搜索",
    "police.errorLoading": "載入警察局數據失敗",
    "police.tryAgain": "重試",
    "police.loaded": "已載入",

    // Police Districts (Traditional Chinese)
    "district.Hong Kong Island": "香港島",
    "district.Kowloon East": "九龍東",
    "district.Kowloon West": "九龍西",
    "district.Marine Region": "水警區",
    "district.New Territories North": "新界北",
    "district.New Territories South": "新界南",

    // Police Services (Traditional Chinese)
    "service.Control Point Police Reporting Centre": "管制站警務報案中心",
    "service.Police Post": "警崗",
    "service.Police Reporting Centre": "警務報案中心",
    "service.Police Services Centre": "警務服務中心",
    "service.Report Room": "報案室",

    // Police Station Names (Traditional Chinese)
    "station.Airport District": "機場區",
    "station.Ap Lei Chau Division": "鴨脷洲分區",
    "station.Central District": "中區",
    "station.Cheung Chau Division": "長洲分區",
    "station.Cheung Sha Wan Division": "長沙灣分區",
    "station.Choi Hung Division": "彩虹分區",
    "station.Eastern District": "東區",
    "station.Fo Tan Division": "火炭分區",
    "station.Heung Yuen Wai Boundary Control Point Police Reporting Centre": "香園圍邊界管制站警務報案中心",
    "station.Kai Tak Cruise Terminal Police Reporting Centre": "啟德郵輪碼頭警務報案中心",
    "station.Kam Tin Division": "錦田分區",
    "station.Kowloon Bay Division": "九龍灣分區",
    "station.Kowloon City Division": "九龍城分區",
    "station.Kwai Chung Division": "葵涌分區",
    "station.Kwun Tong Division": "觀塘分區",
    "station.Lamma Island Police Post": "南丫島警崗",
    "station.Lo Wu Control Point": "羅湖管制站",
    "station.Lok Ma Chau Boundary Control Point": "落馬洲邊界管制站",
    "station.Ma On Shan Division": "馬鞍山分區",
    "station.Ma Tau Wai Division": "馬頭圍分區",
    "station.Man Kam To Boundary Control Point": "文錦渡邊界管制站",
    "station.Marine East Division": "水警東分區",
    "station.Marine North Division": "水警北分區",
    "station.Marine South Division": "水警南分區",
    "station.Marine West Division": "水警西分區",
    "station.Mong Kok Division": "旺角分區",
    "station.Ngau Tau Kok Division": "牛頭角分區",
    "station.North Point Division": "北角分區",
    "station.Peng Chau Police Post": "坪洲警崗",
    "station.Police Services Centre, Central District": "警務服務中心，中區",
    "station.Sai Kung Division": "西貢分區",
    "station.Sha Tin Division": "沙田分區",
    "station.Sham Shui Po Division": "深水埗分區",
    "station.Shatin Pass Division": "沙田坳分區",
    "station.Shek Kip Mei Division": "石硤尾分區",
    "station.Shenzhen Bay Port Reporting Centre": "深圳灣口岸報案中心",
    "station.Southern District": "南區",
    "station.Tai Hang Division": "大坑分區",
    "station.Tai Po Division": "大埔分區",
    "station.Tai Wai Division": "大圍分區",
    "station.Tin Shui Wai Division": "天水圍分區",
    "station.Tsing Yi Division": "青衣分區",
    "station.Tsuen Wan Division": "荃灣分區",
    "station.Tuen Mun Division": "屯門分區",
    "station.Tung Chung Division": "東涌分區",
    "station.Wan Chai Division": "灣仔分區",
    "station.West Kowloon Division": "西九龍分區",
    "station.Wong Tai Sin Division": "黃大仙分區",
    "station.Yau Ma Tei Division": "油麻地分區",
    "station.Yau Tsim Division": "油尖分區",
    "station.Yuen Long Division": "元朗分區",

    // Parks (Traditional Chinese)
    "parks.parksAndRecreation": "公園與娛樂",
    "parks.findParks": "查找公園和休閒區",
    "parks.totalParks": "總計公園",
    "parks.withDirections": "可導航",
    "parks.districts": "區域",
    "parks.parkTypes": "公園類型",
    "parks.allDistricts": "所有區域",
    "parks.allTypes": "所有類型",
    "parks.searchPlaceholder": "搜索公園...",
    "parks.showFilters": "顯示篩選",
    "parks.hideFilters": "隱藏篩選",
    "parks.clear": "清除",
    "parks.parkType": "公園類型",
    "parks.address": "地址",
    "parks.coordinatesUnavailable": "此公園無確切坐標",
    "parks.directions": "導航",
    "parks.search": "搜索",
    "parks.noParks": "未找到公園",
    "parks.noMatches": "沒有公園符合您的搜索",
    "parks.errorLoading": "載入公園數據失敗",
    "parks.tryAgain": "重試",
    "parks.loaded": "已載入",
    "parks.addressOnly": "僅地址",

    // Park Districts (Traditional Chinese)
    "parkDistrict.hong_kong_island": "香港島",
    "parkDistrict.kowloon_east": "九龍東",
    "parkDistrict.kowloon_west": "九龍西",
    "parkDistrict.new_territories_north": "新界北",
    "parkDistrict.new_territories_south": "新界南",
    "parkDistrict.islands": "離島",
    "parkDistrict.other": "其他",

    // Park Types (Traditional Chinese)
    "parkType.public_park": "公共公園",
    "parkType.country_park": "郊野公園",
    "parkType.beach_park": "海濱公園",
    "parkType.garden": "花園",
    "parkType.recreation_ground": "遊樂場",
    "parkType.playground": "兒童遊樂場",
    "parkType.sports_ground": "體育場",
    "parkType.swimming_pool": "游泳池",
    "parkType.waterfront_park": "海濱公園",

    // Hospital Names (Traditional Chinese)
    "hospital.AHNH": "雅麗氏何妙齡那打素醫院",
    "hospital.CGH": "明愛醫院",
    "hospital.KWH": "廣華醫院",
    "hospital.PMH": "瑪嘉烈醫院",
    "hospital.QEH": "伊利沙白醫院",
    "hospital.QMH": "瑪麗醫院",
    "hospital.RHTSK": "律敦治醫院",
    "hospital.TMH": "屯門醫院",
    "hospital.UCH": "基督教聯合醫院",
    "hospital.WWH": "仁濟醫院",
    "hospital.PYNEH": "東區尤德夫人那打素醫院",
    "hospital.TKOH": "將軍澳醫院",
    "hospital.NLTH": "北大嶼山醫院",
    "hospital.HKEH": "香港眼科醫院",
    "hospital.NDH": "北區醫院",
    "hospital.PWH": "威爾斯親王醫院",
    "hospital.TSH": "天水圍醫院",
    "hospital.POH": "博愛醫院",
    "hospital.SJH": "聖約翰醫院",
    "hospital.HKBH": "香港浸信會醫院",
    "hospital.HKSH": "香港養和醫院",

    // Hospital Addresses (Traditional Chinese)
    "address.AHNH": "新界大埔全安路11號",
    "address.CGH": "九龍深水埗永康街111號",
    "address.KWH": "九龍油麻地窩打老道25號",
    "address.PMH": "九龍荔枝角瑪嘉烈醫院道2-10號",
    "address.QEH": "九龍油麻地加斯科尼道30號",
    "address.QMH": "香港薨美薨美道102號",
    "address.RHTSK": "香港灣仔皇后大道東266號",
    "address.TMH": "新界屯門青松觀路23號",
    "address.UCH": "九龍觀塘協和街130號",
    "address.WWH": "新界荿灣仁濟街7-29號",
    "address.PYNEH": "香港柴灣樂民道3號",
    "address.TKOH": "新界將軍澳坑口寶寧里2號",
    "address.NLTH": "新界大嶼山赤鱲角南路8號",
    "address.HKEH": "九龍旺角亞皮路147K號",
    "address.NDH": "新界上水保健路9號",
    "address.PWH": "新界沙田銀城街30-32號",
    "address.TSH": "新界天水圍天壇街2號",
    "address.POH": "新界荿灣青山公路99號",
    "address.SJH": "香港半山區麥當勞道2號",
    "address.HKBH": "九龍九龍塘窩打老道222號",
    "address.HKSH": "香港跑馬地山村道2號",

    // District Clusters (Traditional Chinese)
    "cluster.hongKongEast": "香港東區",
    "cluster.hongKongWest": "香港西區",
    "cluster.kowloonCentral": "九龍中區",
    "cluster.kowloonEast": "九龍東區",
    "cluster.kowloonWest": "九龍西區",
    "cluster.newTerritoriesEast": "新界東區",
    "cluster.newTerritoriesWest": "新界西區",

    // Authentication (Traditional Chinese)
    "auth.createAccount": "建立帳戶",
    "auth.joinCommunity": "加入我們的社群開始使用",
    "auth.signIn": "登入",
    "auth.welcomeBack": "歡迎回來",
    "auth.username": "用戶名",
    "auth.email": "電郵",
    "auth.password": "密碼",
    "auth.confirmPassword": "確認密碼",
    "auth.createAccountButton": "建立帳戶",
    "auth.signInButton": "登入",
    "auth.creatingAccount": "建立帳戶中...",
    "auth.signingIn": "登入中...",
    "auth.alreadyHaveAccount": "已有帳戶？",
    "auth.signInHere": "點擊登入",
    "auth.dontHaveAccount": "沒有帳戶？",
    "auth.createOne": "建立帳戶",
    "auth.accountCreated": "帳戶建立成功！請查看電郵驗證您的帳戶。",
    "auth.invalidCredentials": "登入憑據無效",
    "auth.usernameTaken": "用戶名已被佔用",
    "auth.usernameAvailable": "用戶名可用！",
    "auth.checkingAvailability": "檢查可用性中...",
    "auth.usernameInvalid": "用戶名必須以@開頭，只能包含字母、數字和下劃線（4-20個字符）",
    "auth.chooseUsername": "選擇一個以@開頭的唯一用戶名",
    "auth.fillAllFields": "請填寫所有欄位",
    "auth.enterValidUsername": "請輸入有效的用戶名",
    "auth.chooseAvailableUsername": "請選擇一個可用的用戶名",
    "auth.enterValidEmail": "請輸入有效的電郵地址",
    "auth.passwordTooShort": "密碼必須至少6個字符",
    "auth.passwordsDontMatch": "密碼不匹配",
    "auth.passwordMinLength": "至少6個字符",
    "auth.enterEmail": "輸入您的電郵",
    "auth.enterPassword": "輸入您的密碼",
    "auth.createPassword": "建立密碼",
    "auth.confirmYourPassword": "確認您的密碼",
    "auth.signInRequired": "需要登入",
    "auth.signInToBookmark": "請登入以收藏文章供以後閱讀。",
    "auth.needAccount": "需要帳戶？",
    "auth.haveAccount": "已有帳戶？",

    // Menu (Traditional Chinese)
    "menu.title": "選單",
    "menu.signIn": "登入",
    "menu.signUp": "註冊",
    "menu.settingsInfo": "設定和資訊",
    "menu.enterDetails": "請在下方輸入您的詳細資訊",
    "menu.account": "帳戶",
    "menu.systemStatus": "系統狀態",
    "menu.theme": "主題",
    "menu.loading": "載入中...",
    "menu.backToMenu": "返回選單",
    "menu.closeMenu": "關閉選單",

    // Real-time updates
    "realtime.active": "實時更新已啟動",
    "realtime.connecting": "正在連接實時更新...",

    // Bookmarks Empty State
    "bookmarks.emptyState.title": "您的閱讀清單正在等待",
    "bookmarks.emptyState.description": "保存對您重要的文章。\n隨時隨地閱讀。",
    
    // Bookmarks Search
    "bookmarks.search.placeholder": "搜尋書籤...",
    "bookmarks.search.noResults": "未找到書籤",
    "bookmarks.search.noResultsDesc": "沒有書籤匹配 \"{query}\"。請嘗試其他搜尋詞。",
    "bookmarks.search.clearSearch": "清除搜尋",

    // Filter Categories
    "filters.all": "全部",
    "filters.hkma": "金管局",
    "filters.gov": "政府",
    "filters.road": "道路",
    "filters.transport": "交通",
    "filters.weather": "天氣",
    "filters.health": "健康",
    "filters.hospital": "醫院",
    "filters.utility": "公用",
    "filters.rail": "鐵路",
    "filters.police": "警察",
    "filters.emergency": "緊急",
    "filters.education": "教育",
    "filters.immigration": "移民",
    "filters.environment": "環境",

    // Bulletin
    "bulletin.noContent": "內容尚未可用",
    "bulletin.readMore": "閱讀更多",
    "bulletin.viewOriginal": "查看原文",

    // News Outlets
    "outlets.allSources": "所有來源",
    "outlets.Bloomberg": "彭博社",
    "outlets.SCMP": "南華早報",
    "outlets.HKFP": "香港自由新聞",
    "outlets.RTHK": "香港電台",
    "outlets.HK01": "香港01",
    "outlets.TVB": "無綫電視",
    "outlets.AM730": "AM730",
    "outlets.HKEJ": "信報財經新聞",
    "outlets.On.cc": "東網",
    "outlets.SingTao": "星島日報",
    "outlets.Ming Pao": "明報",
    "outlets.Oriental Daily": "東方日報",
    "outlets.The Standard": "英文虎報",
    "outlets.Now News": "Now新聞",
    "outlets.InMedia": "香港獨立媒體",
    "outlets.Coconuts Hong Kong": "椰子香港",
    "outlets.Hong Kong Government News": "香港政府新聞",
    "outlets.Bastille Post": "巴士的報",
    "outlets.Metro Radio": "新城電台",
    "outlets.Commercial Radio": "商業電台",
  },
}

const initialState: LanguageState = {
  language: 'en', // Default to English for SSR
  isHydrated: false,
}

const languageSlice = createSlice({
  name: 'language',
  initialState,
  reducers: {
    setLanguage: (state, action: PayloadAction<Language>) => {
      const previousLanguage = state.language
      state.language = action.payload
      if (typeof window !== 'undefined') {
        localStorage.setItem('panora-language', action.payload)
        
        // Dispatch a custom event for language change
        const event = new CustomEvent('language-changed', {
          detail: { from: previousLanguage, to: action.payload }
        })
        window.dispatchEvent(event)
      }
    },
    hydrate: (state) => {
      if (typeof window !== 'undefined') {
        const savedLanguage = localStorage.getItem('panora-language') as Language
        if (savedLanguage && ['en', 'zh-CN', 'zh-TW'].includes(savedLanguage)) {
          state.language = savedLanguage
        }
      }
      state.isHydrated = true
    },
  },
})

export const { setLanguage, hydrate } = languageSlice.actions

// Selectors
export const selectLanguage = (state: { language: LanguageState }) => state.language.language
export const selectIsHydrated = (state: { language: LanguageState }) => state.language.isHydrated

// Translation function selector
export const selectTranslation = (key: string) => (state: { language: LanguageState }) => {
  const language = state.language.isHydrated ? state.language.language : 'en'
  return translations[language][key] || key
}

export default languageSlice.reducer