"use client"

import { useInfiniteQuery } from "@tanstack/react-query"
import { useEffect, useState } from "react"
import { useInView } from "react-intersection-observer"
import ArticleCard from "./article-card"
import ArticleBottomSheet from "./article-bottom-sheet"
import LoadingSkeleton from "./loading-skeleton"
import { useLanguage } from "./language-provider"
import { transformPerplexityToArticle } from "@/lib/perplexity-utils"
import type { Article, PerplexityArticle } from "@/lib/types"

interface PerplexityFeedResponse {
  articles: PerplexityArticle[]
  nextPage: number | null
  usingMockData: boolean
  debug?: string
}

async function fetchPerplexityArticles({ pageParam = 0 }): Promise<PerplexityFeedResponse> {
  const response = await fetch(`/api/perplexity?page=${pageParam}`)
  if (!response.ok) throw new Error("Failed to fetch Perplexity articles")
  return response.json()
}

export default function PerplexityFeed() {
  const { ref, inView } = useInView()
  const { t } = useLanguage()
  const [selectedArticleId, setSelectedArticleId] = useState<string | null>(null)
  const [isBottomSheetOpen, setIsBottomSheetOpen] = useState(false)

  const handleReadMore = (articleId: string) => {
    console.log(`🔍 PerplexityFeed: Opening article with ID: ${articleId}`)
    setSelectedArticleId(articleId)
    setIsBottomSheetOpen(true)
  }

  const handleBottomSheetChange = (open: boolean) => {
    setIsBottomSheetOpen(open)
    if (!open) {
      setSelectedArticleId(null)
    }
  }

  const { data, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading, error } = useInfiniteQuery({
    queryKey: ["perplexity-articles"],
    queryFn: ({ pageParam }) => {
      console.log("🔄 Fetching perplexity articles, page:", pageParam)
      return fetchPerplexityArticles({ pageParam })
    },
    getNextPageParam: (lastPage) => {
      console.log("📊 GetNextPageParam - lastPage.nextPage:", lastPage.nextPage)
      return lastPage.nextPage
    },
    initialPageParam: 0,
    staleTime: 2 * 60 * 1000, // 2 minutes (refresh more frequently for AI-generated content)
    refetchInterval: 5 * 60 * 1000, // Refetch every 5 minutes
  })

  useEffect(() => {
    if (inView && hasNextPage) {
      fetchNextPage()
    }
  }, [inView, hasNextPage, fetchNextPage])

  if (isLoading) return <LoadingSkeleton />
  if (error) return <div className="p-4 text-center text-destructive" suppressHydrationWarning>{t("error.failedToLoad")} AI news</div>

  const perplexityArticles = data?.pages.flatMap((page) => page.articles) ?? []
  const articles: Article[] = perplexityArticles.map(transformPerplexityToArticle)
  
  console.log(`📊 PerplexityFeed: Loaded ${articles.length} articles, first article:`, articles[0]?.id, articles[0]?.title)

  if (articles.length === 0) {
    return (
      <div className="p-6 text-center">
        <h3 className="text-lg font-semibold text-stone-900 dark:text-neutral-50 mb-2">
          {t("perplexity.noNews") || "No AI news available"}
        </h3>
        <p className="text-stone-600 dark:text-neutral-400">
          {t("perplexity.waitingForContent") || "Fresh AI-generated content is being created..."}
        </p>
      </div>
    )
  }

  return (
    <div className="px-6 pb-4">
      {/* Header for AI news */}
      <div className="mb-6">
        <h2 className="text-xl font-semibold text-stone-900 dark:text-neutral-50 mb-2">
          {t("perplexity.aiNewsFeed") || "AI News Feed"}
        </h2>
        <p className="text-sm text-stone-600 dark:text-neutral-400">
          {t("perplexity.aiNewsDescription") || "Fresh Hong Kong news generated by AI, updated every 5 minutes"}
        </p>
      </div>

      {/* Responsive grid layout: mobile 1col, tablet 2col, desktop 3col, large 4col */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-6">
        {articles.map((article) => (
          <ArticleCard 
            key={article.id} 
            article={article} 
            onReadMore={handleReadMore}
          />
        ))}
      </div>

      <div ref={ref} className="h-10">
        {isFetchingNextPage && <LoadingSkeleton />}
      </div>

      {/* Show mock data indicator if applicable */}
      {data?.pages[0]?.usingMockData && (
        <div className="mt-8 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
          <p className="text-sm text-blue-800 dark:text-blue-200">
            {t("perplexity.usingMockData") || "Using sample AI-generated content. Live content will appear when the system is fully configured."}
          </p>
        </div>
      )}

      <ArticleBottomSheet
        articleId={selectedArticleId}
        open={isBottomSheetOpen}
        onOpenChange={handleBottomSheetChange}
      />
    </div>
  )
}