export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import OpenAI from 'openai';
import { toFile } from 'openai/uploads';
import sharp from 'sharp';
import { randomUUID } from 'crypto';
import { autoProcessArticleImage } from '@/lib/image-processor';

// ---------- CONFIG ----------
const OPENAI_TIMEOUT_MS = 300_000; // allow long image jobs
const DEFAULT_SIZE = '1792x1024'; // 16:9 aspect ratio for DALL-E 3
const BUCKET = 'article-images';
const PREFIX = 'articles';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase = createClient(supabaseUrl, supabaseKey);

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
  timeout: OPENAI_TIMEOUT_MS,
});

// Use GPT-4 to generate contextual DALL-E prompt based on article content
async function generateContextualPrompt(article: any): Promise<string> {
  const title = article?.title || ''
  const content = article?.content || ''
  const summary = article?.summary || ''
  const category = article?.category || ''
  
  const systemPrompt = `You are a senior photo editor at a leading Hong Kong news agency. Your job is to write ONE DALL·E 3 prompt that produces a photorealistic, editorial-quality news photograph suitable for front-page use.
CONTEXT: You work for a Hong Kong-based news organization that requires authentic, professional photojournalistic images that capture the essence of news stories while maintaining the highest editorial standards.

GOALS
- Authentic Hong Kong context, people, and atmosphere.
- Photojournalistic style consistent with Reuters/AP/AFP.
- Truthful, non-sensational, minimally processed look.

NON-NEGOTIABLES
- No public figures by name or likeness. No logos, trademarks, or text of any kind.
- Avoid cinematic/CGI aesthetics (e.g., “Unreal Engine,” “Octane,” “8k wallpaper,” “hyperreal,” “render”).
- Neutral, documentary tone; no propaganda or stereotypes.

TECH SPECS HINTS (embed naturally in the prompt)
- Camera: Nikon D850 or Canon 5D Mark IV
- Lens: 24–70mm (context), 50mm (street/medium), 85mm (portrait)
- Typical settings: f/5.6–f/8 for scenes; f/2.8 for portraits; 1/500–1/1000s for motion; ISO 100–800
- Lighting: natural daylight, overcast, or golden hour; or discreet on-camera flash for night spot news
- Composition: clean framing; horizon straight; rule of thirds or central framing when justified
- Post: minimal, newsroom-standard color and contrast

HK CONTEXT HINTS (embed specifics)
- Micro-locations: name a district and a precise setting (e.g., “Mong Kok wet market on Fa Yuen Street,” “Central outside Exchange Square,” “Sham Shui Po street market,” “Tsim Sha Tsui promenade”).
- Atmosphere/props: MTR signage (generic, no text), minibus/taxis (unbranded), wet market stalls, tong lau facades, Octopus gates (no text).
- People: diverse Hong Kong residents (age/gender mix; Cantonese majority; some expats), candid interactions, natural clothing.

NEGATIVE LIST (include at end of prompt)
Exclude: text overlays, watermarks, brand logos, celebrity/politician likenesses, AI art artifacts, heavy bokeh balls, extreme color grading, tilt-shift, motion trails that look artificial.

OUTPUT
- Return only the DALL·E prompt text (no preamble, no quotes, no numbering).
- Use one crisp paragraph in natural language.`

  const userPrompt = `Create a DALL-E prompt for this Hong Kong news article:

Title: ${title}
Category: ${category}
Summary: ${summary}
Content: ${content.slice(0, 1500)}

Generate a prompt that will create a professional news photograph that captures the essence of this story with authentic Hong Kong context.`

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      max_tokens: 500,
      temperature: 0.7
    })

    const prompt = response.choices[0]?.message?.content?.trim()
    if (!prompt) {
      throw new Error('No prompt generated by GPT-4')
    }

    return prompt
  } catch (error) {
    console.error('Error generating contextual prompt:', error)
    // Fallback to a basic Hong Kong news scene
    return `Professional news photograph of Hong Kong urban scene, diverse crowd of people, modern city life, authentic street photography, Ultra-realistic photojournalism, World-class news agency photographer quality, Professional Nikon D850, 85mm lens, Natural lighting, High resolution editorial quality, No text overlays, Hyper-realistic magazine quality`
  }
}

// ---------- HELPERS ----------
async function fetchAsBuffer(url: string, abortMs = 60_000): Promise<Buffer> {
  const ac = new AbortController();
  const t = setTimeout(() => ac.abort(), abortMs);
  try {
    const res = await fetch(url, { signal: ac.signal });
    if (!res.ok) throw new Error(`Failed to fetch image: ${res.status} ${res.statusText}`);
    const arrayBuf = await res.arrayBuffer();
    return Buffer.from(arrayBuf);
  } finally {
    clearTimeout(t);
  }
}

async function preprocessImageToPng(input: Buffer, maxDim = 2048): Promise<Buffer> {
  // Keeps within 2048px limit to reduce transfer & processing time
  return sharp(input)
    .resize({ width: maxDim, height: maxDim, fit: 'inside', withoutEnlargement: true })
    .png()
    .toBuffer();
}

async function uploadToSupabase(buffer: Buffer, articleId: string, contentType = 'image/png') {
  const fileName = `gpt4-dalle3-${articleId}-${Date.now()}.png`;
  const storagePath = `${PREFIX}/${articleId}/${fileName}`;
  const { error } = await supabase.storage.from(BUCKET).upload(storagePath, buffer, {
    contentType,
    upsert: false,
  });
  if (error) throw error;
  const { data } = supabase.storage.from(BUCKET).getPublicUrl(storagePath);
  return { storagePath, publicUrl: data.publicUrl };
}

async function runWithRetry<T>(fn: () => Promise<T>, tries = 2): Promise<T> {
  let lastErr: any;
  for (let i = 0; i < tries; i++) {
    try {
      return await fn();
    } catch (e: any) {
      lastErr = e;
      // Retry only on transient connection failures
      const msg = (e?.message || '').toLowerCase();
      if (
        !msg.includes('apiconnectionerror') &&
        !msg.includes('und_err_socket') &&
        !msg.includes('socket') &&
        !msg.includes('fetch failed') &&
        !msg.includes('timeout')
      ) {
        break;
      }
      await new Promise((r) => setTimeout(r, 1000 * (i + 1) + Math.floor(Math.random() * 500)));
    }
  }
  throw lastErr;
}

// ---------- ROUTE ----------
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { imageUrl, articleId } = body;

    if (!imageUrl || !articleId) {
      return NextResponse.json(
        { error: 'Image URL and Article ID are required' },
        { status: 400 }
      );
    }

    // Fetch article details for context
    console.log('Fetching article details...');
    const { data: article, error: fetchError } = await supabase
      .from('articles')
      .select('id, title, summary, category, content')
      .eq('id', articleId)
      .single();

    if (fetchError || !article) {
      console.warn('Could not fetch article for context:', fetchError);
    }

    // Step 1: Use GPT-4 to generate contextual DALL-E prompt
    console.log('Using GPT-4 to analyze article and generate contextual prompt...');
    const prompt = await generateContextualPrompt(article);
    console.log('GPT-4 generated DALL-E prompt:', prompt);

    // Step 2: Use DALL-E 3 to generate image from GPT-4 prompt
    console.log('Calling DALL-E 3 API with GPT-4 generated prompt...');
    const res = await runWithRetry(() =>
      openai.images.generate({
        model: 'dall-e-3',
        prompt,
        size: DEFAULT_SIZE,
        quality: 'hd',
        style: 'natural',
        n: 1
      })
    );

    const generatedImageUrl = res.data?.[0]?.url;
    if (!generatedImageUrl) throw new Error('No image returned from DALL-E 3 generation');
    
    // Download the generated image
    const genBuffer = await fetchAsBuffer(generatedImageUrl);

    // Upload to Supabase
    console.log('Uploading generated image to Supabase...');
    const { publicUrl, storagePath } = await uploadToSupabase(genBuffer, articleId, 'image/png');

    // Update article with new image URL
    const { error: updateError } = await supabase
      .from('articles')
      .update({ image_url: publicUrl })
      .eq('id', articleId);

    if (updateError) {
      console.error('Article update error:', updateError);
      throw new Error(`Failed to update article: ${updateError.message}`);
    }

    console.log('Article updated successfully with DALL-E 3 generated image');

    // Auto-process the OpenAI-generated image for social media previews
    // Use forceReprocess=true to ensure we process the new OpenAI image even if metadata exists
    autoProcessArticleImage(articleId, publicUrl, 'articles', true).catch(error => {
      console.error(`Failed to process OpenAI-generated image for article ${articleId}:`, error)
    })

    return NextResponse.json({
      success: true,
      imageUrl: publicUrl,
      storagePath,
      articleId,
      message: 'Professional editorial image generated successfully with GPT-4 + DALL-E 3',
    });
  } catch (error: any) {
    console.error('OpenAI image generation error:', error);
    const status = String(error?.message || '').toLowerCase().includes('apiconnectionerror') ? 504 : 500;
    return NextResponse.json(
      { error: error?.message || 'Failed to generate image' },
      { status },
    );
  }
}