import { type NextRequest, NextResponse } from "next/server"
import { supabaseAdmin } from "@/lib/supabase-server"

export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    console.log("🔄 Starting perplexity schema migration...")

    // Add enhanced structured content fields to perplexity_news table
    const migrationSQL = `
      -- Add enhanced structured content fields to perplexity_news table
      ALTER TABLE perplexity_news 
      ADD COLUMN IF NOT EXISTS enhanced_title TEXT,
      ADD COLUMN IF NOT EXISTS summary TEXT,
      ADD COLUMN IF NOT EXISTS key_points TEXT[],
      ADD COLUMN IF NOT EXISTS why_it_matters TEXT,
      ADD COLUMN IF NOT EXISTS structured_sources JSONB;

      -- Add indexes for performance
      CREATE INDEX IF NOT EXISTS idx_perplexity_enhanced_title ON perplexity_news(enhanced_title);
      CREATE INDEX IF NOT EXISTS idx_perplexity_summary ON perplexity_news(summary);
      CREATE INDEX IF NOT EXISTS idx_perplexity_structured_sources ON perplexity_news USING GIN(structured_sources);

      -- Add comments to document the enhancement
      COMMENT ON COLUMN perplexity_news.enhanced_title IS 'Improved, engaging headline generated by AI';
      COMMENT ON COLUMN perplexity_news.summary IS 'Executive summary of the article (2-3 sentences)';
      COMMENT ON COLUMN perplexity_news.key_points IS 'Array of key points from the article';
      COMMENT ON COLUMN perplexity_news.why_it_matters IS 'Analysis of broader significance and impact';
      COMMENT ON COLUMN perplexity_news.structured_sources IS 'Source citations in structured JSON format';
    `

    // Execute migration
    const { error } = await supabaseAdmin.rpc('exec_sql', { sql: migrationSQL })
    
    if (error) {
      // If rpc doesn't exist, try direct SQL execution
      const { error: directError } = await supabaseAdmin.from('perplexity_news').select('enhanced_title').limit(1)
      
      if (directError && directError.code === 'PGRST204') {
        console.error("❌ Migration failed - enhanced fields still missing")
        return NextResponse.json({
          success: false,
          error: "Migration failed - enhanced fields not available. Please run the migration manually in the database.",
          details: directError.message
        }, { status: 500 })
      }
    }

    // Test if migration was successful
    const { error: testError } = await supabaseAdmin
      .from('perplexity_news')
      .select('enhanced_title, summary, key_points, why_it_matters, structured_sources')
      .limit(1)

    if (testError) {
      console.error("❌ Migration test failed:", testError)
      return NextResponse.json({
        success: false,
        error: "Migration test failed",
        details: testError.message
      }, { status: 500 })
    }

    console.log("✅ Perplexity schema migration completed successfully")

    return NextResponse.json({
      success: true,
      timestamp: new Date().toISOString(),
      message: "Enhanced perplexity fields migration completed successfully",
      fields_added: [
        "enhanced_title",
        "summary", 
        "key_points",
        "why_it_matters",
        "structured_sources"
      ]
    })

  } catch (error) {
    console.error("💥 Perplexity schema migration failed:", error)

    return NextResponse.json({
      success: false,
      timestamp: new Date().toISOString(),
      error: "Migration failed",
      details: error.message,
      solution: "Please run the migration script manually: scripts/add-enhanced-perplexity-fields.sql"
    }, { status: 500 })
  }
}