"use client"

import UnifiedFeed from "./unified-feed"
import { useLanguage } from "./language-provider"

/**
 * PerplexityFeed component reimplemented using UnifiedFeed
 * This demonstrates how to migrate existing feed components to the unified system
 * 
 * Migration notes:
 * - All the complex logic is now handled by UnifiedFeed
 * - Configuration is passed via props
 * - The feed type 'ai' maps to article_type='ai_generated' in the database
 * - Refresh interval and other behaviors are configured via the config prop
 */
export default function PerplexityFeed() {
  const { t } = useLanguage()

  return (
    <UnifiedFeed 
      config={{
        feedType: 'ai',
        refreshInterval: 2 * 60 * 1000, // Auto-refresh every 2 minutes
        showRefreshButton: true,
        enableInfiniteScroll: true,
        pageSize: 10
      }}
      headerConfig={{
        title: t("perplexity.aiNewsFeed") || "AI News Feed",
        subtitle: t("perplexity.aiNewsDescription") || "Fresh Hong Kong news generated by AI, sorted by latest updates",
        showRefresh: true
      }}
    />
  )
}

/**
 * Alternative: Direct usage in pages
 * 
 * Instead of using this wrapper, you can use UnifiedFeed directly in your pages:
 * 
 * ```tsx
 * import UnifiedFeed from "@/components/unified-feed"
 * 
 * function MyPage() {
 *   return (
 *     <UnifiedFeed 
 *       config={{ feedType: 'ai', refreshInterval: 120000 }}
 *       headerConfig={{ title: "AI News" }}
 *     />
 *   )
 * }
 * ```
 * 
 * Benefits of direct usage:
 * - More flexibility in configuration
 * - Can easily add custom filters
 * - Can combine multiple feed types
 */