-- Migration script to add enhanced perplexity enrichment fields
-- This script adds the new structured content fields to existing perplexity_news table

-- Add enhanced structured content fields to perplexity_news table
ALTER TABLE perplexity_news 
ADD COLUMN IF NOT EXISTS enhanced_title TEXT,
ADD COLUMN IF NOT EXISTS summary TEXT,
ADD COLUMN IF NOT EXISTS key_points TEXT[],
ADD COLUMN IF NOT EXISTS why_it_matters TEXT,
ADD COLUMN IF NOT EXISTS structured_sources JSONB;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_perplexity_enhanced_title ON perplexity_news(enhanced_title);
CREATE INDEX IF NOT EXISTS idx_perplexity_summary ON perplexity_news(summary);
CREATE INDEX IF NOT EXISTS idx_perplexity_structured_sources ON perplexity_news USING GIN(structured_sources);

-- Add comment to document the enhancement
COMMENT ON COLUMN perplexity_news.enhanced_title IS 'Improved, engaging headline generated by AI';
COMMENT ON COLUMN perplexity_news.summary IS 'Executive summary of the article (2-3 sentences)';
COMMENT ON COLUMN perplexity_news.key_points IS 'Array of key points from the article';
COMMENT ON COLUMN perplexity_news.why_it_matters IS 'Analysis of broader significance and impact';
COMMENT ON COLUMN perplexity_news.structured_sources IS 'Source citations in structured JSON format';

-- Migration complete
SELECT 'Enhanced perplexity enrichment fields added successfully' AS result;